import { useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';

// keyword map: emoji → space-separated search terms
const names = {
  '😀':'grinning happy smile laugh','😃':'happy smile open','😄':'grin smile happy','😁':'beam grin teeth','😆':'laugh happy squinting','😅':'nervous laugh sweat smile','😂':'joy tears laugh crying lol','🤣':'rofl rolling floor laughing','🥲':'smiling tear bittersweet','😊':'blush smile warm','😇':'angel halo innocent','🥰':'hearts love adore','😍':'heart eyes love','🤩':'star eyes excited wow','😘':'kiss wink blow heart','😗':'kiss whistle','😙':'kiss smile','😚':'kiss closed eyes','🙂':'slightly smile','🤭':'hand mouth giggle hehe','😉':'wink','😌':'relieved content calm','😏':'smirk','😒':'unamused meh bored','😞':'disappointed sad','😔':'pensive sad','😟':'worried concerned','😕':'confused unsure','🙁':'frown sad','☹️':'frowning sad','😣':'persevering struggling','😖':'confounded frustrated','😫':'tired weary exhausted','😩':'weary tired','🥺':'pleading puppy eyes sad','😢':'cry sad tear','😭':'sob crying loud','😤':'triumph huff angry','😠':'angry mad','😡':'rage pouting red angry','🤬':'cursing angry symbols','🤯':'exploding mind blown','😳':'flushed embarrassed surprised','🥵':'hot sweating','🥶':'cold freezing','😱':'scream horror shocked','😨':'fearful scared','😰':'anxious nervous sweat','🤔':'thinking ponder','🫡':'salute respect','🤗':'hugging hug warm','😶':'no mouth silent','😑':'expressionless blank','😬':'grimace awkward','🙄':'eye roll annoy','😯':'hushed surprised','😲':'astonished shocked','🥱':'yawn tired bored','😴':'sleeping zzz','😵':'dizzy spiral','🤐':'zipper mouth silent','🥴':'woozy drunk dizzy','🤧':'sneeze sick','😷':'mask sick medical','🤒':'ill thermometer fever','😈':'devil evil grin','👿':'devil angry','💀':'skull dead death','👻':'ghost spooky halloween','😺':'cat grinning','😸':'cat grin','😹':'cat joy laugh','😻':'cat heart eyes love','😎':'cool sunglasses','🤓':'nerd glasses','🧐':'monocle curious examine',
  '❤️':'red heart love','🧡':'orange heart','💛':'yellow heart','💚':'green heart','💙':'blue heart','💜':'purple heart','🖤':'black heart','🤍':'white heart','🤎':'brown heart','💕':'two hearts','💞':'revolving hearts','💓':'beating heart','💗':'growing heart pink','💖':'sparkling heart','💘':'heart arrow cupid love','💝':'heart ribbon gift','💟':'heart decoration','❣️':'heart exclamation','💔':'broken heart','❤️‍🔥':'heart fire passionate','❤️‍🩹':'heart bandage healing','💋':'kiss lips','😘':'kiss face wink heart','🥰':'smiling hearts love','😍':'heart eyes love','🫶':'heart hands','🫂':'hug embrace','💑':'couple love','💏':'kiss couple','💐':'bouquet flowers','🌹':'rose love','🌷':'tulip flower','💒':'wedding chapel','💍':'ring engagement diamond','🎁':'gift present','🪷':'lotus flower','🫧':'bubbles',
  '👋':'wave hello hi goodbye','🤚':'raised hand stop back','🖐️':'hand open spread fingers','✋':'raised hand stop high five','🖖':'vulcan salute prosper','🤙':'shaka call hang loose','👌':'ok perfect','🤌':'pinched fingers','🤏':'pinch small','✌️':'peace victory','🤞':'crossed fingers luck','🤟':'love you hand','🤘':'rock horns metal sign','👈':'left pointing','👉':'right pointing','👆':'up pointing','🖕':'middle finger rude','👇':'down pointing','☝️':'one finger up','👍':'thumbs up like approve good','👎':'thumbs down dislike bad','✊':'fist bump strong','👊':'punch fist','🤛':'left fist bump','🤜':'right fist bump','👏':'clapping applause','🙌':'raising hands celebrate','👐':'open hands','🤲':'cupped hands','🤝':'handshake deal','🙏':'pray thanks please folded','✍️':'writing pen','💅':'nails manicure','🤳':'selfie phone','💪':'muscle strong bicep flex','🦾':'mechanical arm','👀':'eyes look watching','🫦':'lips mouth','🧠':'brain smart think','🫀':'heart organ','🦷':'tooth dental','🦴':'bone',
  '🐶':'dog puppy','🐱':'cat kitten pet','🐭':'mouse','🐹':'hamster','🐰':'rabbit bunny','🦊':'fox sly','🐻':'bear','🐼':'panda','🐨':'koala','🐯':'tiger','🦁':'lion','🐮':'cow moo','🐷':'pig oink','🐸':'frog','🐵':'monkey','🐔':'chicken hen','🐧':'penguin','🐦':'bird','🦆':'duck','🦅':'eagle','🦉':'owl wise','🦇':'bat night','🐺':'wolf','🐴':'horse','🦄':'unicorn magic','🐝':'bee honey','🦋':'butterfly','🐌':'snail slow','🐞':'ladybug','🐜':'ant insect','🦟':'mosquito','🐢':'turtle tortoise','🐍':'snake','🦎':'lizard','🐙':'octopus','🦑':'squid calamari','🦀':'crab seafood','🐡':'puffer fish','🐠':'tropical fish','🐟':'fish','🐬':'dolphin','🐳':'whale big','🐋':'whale spout','🦈':'shark','🦭':'seal','🐘':'elephant trunk','🦒':'giraffe tall','🦓':'zebra stripes','🦍':'gorilla ape','🦏':'rhino','🐊':'crocodile alligator','🦕':'dinosaur sauropod','🦖':'trex dinosaur','🦔':'hedgehog','🐿️':'chipmunk squirrel','🦫':'beaver','🦦':'otter','🦥':'sloth','🦜':'parrot bird','🐓':'rooster crow','🦃':'turkey','🐇':'rabbit white','🐈':'cat pet','🐩':'poodle dog','🦮':'guide dog','🐕':'dog','🐈‍⬛':'black cat','🪲':'beetle bug','🦗':'cricket','🦂':'scorpion',
  '🍎':'apple red fruit','🍊':'orange citrus','🍋':'lemon sour','🍌':'banana yellow','🍉':'watermelon summer','🍇':'grapes wine','🍓':'strawberry','🫐':'blueberry','🍒':'cherries','🍑':'peach','🥭':'mango','🍍':'pineapple','🥝':'kiwi','🍅':'tomato','🥑':'avocado guac','🥦':'broccoli','🥕':'carrot','🌽':'corn cob','🌶️':'pepper spicy hot','🧄':'garlic','🥔':'potato','🍠':'sweet potato','🥐':'croissant pastry','🍞':'bread loaf','🥖':'baguette french','🥨':'pretzel','🧀':'cheese','🥚':'egg','🍳':'fried egg cooking','🥞':'pancakes breakfast','🧇':'waffle breakfast','🥓':'bacon','🥩':'steak meat','🍗':'chicken drumstick','🍖':'meat bone','🍔':'burger hamburger','🍟':'fries chips','🌭':'hotdog','🍕':'pizza','🥪':'sandwich','🌮':'taco mexican','🌯':'wrap burrito','🥗':'salad healthy','🍜':'noodles ramen','🍣':'sushi','🍱':'bento box','🍛':'curry rice','🍲':'stew pot','🍤':'shrimp fried','🍙':'rice ball onigiri','🍚':'rice bowl','🍘':'rice cracker','🍡':'dango sweets','🧁':'cupcake','🎂':'birthday cake celebrate','🍰':'cake slice dessert','🍦':'ice cream soft serve','🍩':'donut doughnut','🍪':'cookie biscuit','🍫':'chocolate','🍭':'lollipop candy','🍬':'candy sweet','☕':'coffee hot','🍵':'tea','🧋':'boba bubble tea','🥤':'drink straw cup','🧃':'juice box','🍺':'beer ale','🍻':'beers cheers','🥂':'champagne toast celebrate','🍷':'wine glass','🍸':'cocktail martini','🍹':'tropical drink','🍾':'champagne bottle','🥃':'whiskey glass','🧊':'ice cube','💧':'water drop',
  '🌸':'cherry blossom spring pink','🌺':'hibiscus tropical','🌻':'sunflower yellow','🌹':'rose flower love','🌷':'tulip','🪷':'lotus','🌱':'seedling grow plant','🌿':'herb green leaf','🍀':'clover luck four leaf','🍃':'leaves','🍂':'autumn fall leaves','🍁':'maple leaf fall canada','🍄':'mushroom','🌾':'wheat grain farm','🌵':'cactus desert','🎄':'christmas tree xmas','🌲':'evergreen pine tree','🌳':'tree park','🎋':'bamboo','🌴':'palm tree tropical','🪴':'potted plant','🪸':'coral reef','🌊':'wave ocean surf sea','🌋':'volcano eruption lava','🏔️':'snow mountain peak','⛰️':'mountain peak','☀️':'sun sunny warm','🌤️':'partly sunny cloudy','⛅':'partly cloudy','🌥️':'cloudy overcast','☁️':'cloud','🌧️':'rain wet umbrella','⛈️':'thunder storm rain','🌩️':'lightning thunder','🌨️':'snow snowflake cold','❄️':'snowflake cold ice winter','☃️':'snowman snow','⛄':'snowman hat','🌈':'rainbow colorful','⚡':'lightning bolt','🔥':'fire flame hot','💧':'drop water','🌬️':'wind blowing','🌀':'cyclone spiral','🌪️':'tornado wind','🌙':'crescent moon night','🌑':'new moon dark','🌕':'full moon bright','⭐':'star night sky','🌟':'glowing star bright','💫':'sparkle dizzy','✨':'sparkles magic','☄️':'comet meteor','🌠':'shooting star','🌌':'galaxy milky way','🌍':'earth globe europe','🌎':'earth americas','🌏':'earth asia pacific','🪐':'planet saturn rings','🌅':'sunrise morning','🌄':'sunrise mountains','🌃':'night city stars','🌆':'cityscape evening','🌇':'sunset city','🌉':'bridge night',
  '✈️':'plane airplane flight','🚀':'rocket space launch','🛸':'ufo flying saucer','🚁':'helicopter','🛩️':'small plane','⛵':'sailboat','🚢':'ship cruise','🚂':'train locomotive steam','🚄':'bullet train fast','🚅':'shinkansen high speed','🚗':'car auto','🚕':'taxi cab yellow','🚙':'suv car','🚌':'bus public transport','🏎️':'racing car fast','🚓':'police car','🚑':'ambulance emergency','🚒':'fire truck','🛻':'pickup truck','🚲':'bicycle bike','🛴':'scooter kick','🛵':'moped scooter','🏍️':'motorcycle motorbike','🚜':'tractor farm','⛽':'fuel gas station','🚦':'traffic light','🚥':'traffic signals','🗺️':'map world navigation','🧭':'compass direction','🏠':'house home','🏡':'house garden home','🏢':'office building','🏦':'bank','🏥':'hospital medical','🏨':'hotel','🏪':'store shop','🏫':'school','🏭':'factory','🏰':'castle medieval','🏯':'japanese castle','🗼':'tokyo tower','🗽':'statue liberty','🗿':'moai stone','🛕':'temple','⛩️':'shinto shrine japan','🕌':'mosque','🎡':'ferris wheel','🎢':'roller coaster','🎠':'carousel','🏖️':'beach vacation sun','🏜️':'desert dry','🏝️':'island tropical','🏕️':'camping tent','🧳':'luggage suitcase','🪂':'parachute skydiving',
  '⚽':'soccer football kick','🏀':'basketball hoop','🏈':'american football','⚾':'baseball bat','🥎':'softball','🏐':'volleyball','🏉':'rugby','🎾':'tennis racket','🥏':'frisbee disc','🎱':'billiards pool','🏓':'ping pong table tennis','🏸':'badminton','🥊':'boxing gloves punch','🥋':'martial arts karate','⛳':'golf flag','🎣':'fishing rod','🤿':'diving snorkel scuba','🏋️':'weightlifting gym strong','🤸':'gymnastics cartwheel','🏊':'swimming pool','🚴':'cycling bike ride','🧘':'yoga meditation','⛷️':'skiing snow','🏂':'snowboard','🤺':'fencing sword','🏇':'horse racing','🧗':'climbing rock wall','🤼':'wrestling','🤾':'handball','⛹️':'basketball dribble','🏌️':'golf swing','🏆':'trophy champion win','🥇':'gold medal first','🥈':'silver medal second','🥉':'bronze medal third','🏅':'medal award','🎖️':'military medal','🎭':'theater drama performing','🎨':'art paint palette','🎬':'film clapper movie','🎤':'microphone sing karaoke','🎧':'headphones music listen','🎼':'music score notes','🎵':'musical note','🎶':'musical notes song','🎹':'piano keyboard music','🥁':'drum beat rhythm','🎷':'saxophone jazz','🎺':'trumpet brass','🎸':'guitar rock','🪕':'banjo country','🎻':'violin strings','🪗':'accordion','🎲':'dice game random','♟️':'chess strategy board','🎮':'video game controller','🕹️':'joystick arcade','🧩':'puzzle jigsaw piece','🎯':'target bullseye aim','🎳':'bowling strike','🎰':'slot machine casino','🪄':'magic wand wizard','🎪':'circus tent','🎉':'party celebrate confetti','🎊':'confetti ball party','🎈':'balloon party','🎀':'ribbon bow gift','🎁':'gift present wrap','🎗️':'ribbon reminder awareness',
  '💼':'briefcase work business','📅':'calendar schedule date','📊':'bar chart data analytics','📈':'chart upward growth','📉':'chart downward decline','🧾':'receipt invoice bill','💻':'laptop computer','🖥️':'desktop monitor','🖨️':'printer','⌨️':'keyboard typing','🖱️':'computer mouse click','📱':'smartphone mobile','☎️':'telephone call','📞':'handset call','📟':'pager beeper','📠':'fax machine','📧':'email message','📝':'memo notes write','✏️':'pencil write draw','🖊️':'pen write','🖋️':'fountain pen formal','📎':'paperclip attach','📌':'pushpin pinned','📍':'location pin','🔒':'locked secure','🔓':'unlocked open','🗂️':'card index dividers','📂':'open folder','📁':'folder directory','📋':'clipboard paste','📜':'scroll document','📄':'page document file','📃':'page curl','⏰':'alarm clock wake','⏱️':'stopwatch time','⌚':'watch wristwatch','💰':'money bag cash rich','💵':'dollar bill money','💳':'credit card payment','🏦':'bank finance','📣':'megaphone announce','📢':'loudspeaker broadcast','💡':'idea lightbulb bright','🎯':'goal target bullseye','🏆':'trophy achievement','🔑':'key unlock access','🗝️':'key vintage old','✅':'check tick done approve yes','❌':'cross wrong no cancel','⚠️':'warning caution','💎':'diamond jewel valuable','🤝':'handshake deal agree','📬':'mailbox incoming','📫':'mailbox closed','🗃️':'card file box','🗄️':'file cabinet','📦':'package box shipping','🌐':'globe internet web','🔭':'telescope','🔬':'microscope science','🧪':'test tube lab experiment','🛡️':'shield protect secure','🔐':'locked key','🪪':'id card identity',
  '💯':'hundred percent perfect','✅':'check done correct yes','❌':'cross wrong no','⭕':'circle red','❗':'exclamation important alert','❓':'question unknown','‼️':'double exclamation','⁉️':'exclamation question','🔴':'red circle','🟠':'orange circle','🟡':'yellow circle','🟢':'green circle','🔵':'blue circle','🟣':'purple circle','⚫':'black circle dark','⚪':'white circle light','🟤':'brown circle','⬆️':'up arrow north','⬇️':'down arrow south','⬅️':'left arrow west','➡️':'right arrow east','↗️':'up right northeast','↘️':'down right southeast','↙️':'down left southwest','↖️':'up left northwest','↕️':'up down vertical','↔️':'left right horizontal','🔄':'refresh arrows counterclockwise','🔃':'clockwise arrows sync','🔁':'repeat loop','🔂':'repeat once','▶️':'play button start','⏩':'fast forward','⏭️':'next track skip','⏯️':'play pause toggle','⏸️':'pause stop','⏹️':'stop square','⏺️':'record red','🆕':'new button','🆗':'ok button','🆒':'cool button','🆓':'free button','🆙':'up button','🔔':'bell notification alert','🔕':'bell mute silence','🔇':'mute volume off','🔊':'volume loud speaker','💬':'speech bubble chat message','💭':'thought bubble think','🗯️':'anger speech','♻️':'recycle green environment','✴️':'star asterisk','🔰':'beginner badge japanese','💠':'diamond blue decoration','🔮':'crystal ball fortune magic','🔸':'orange diamond small','🔹':'blue diamond small','🔺':'red triangle up','🔻':'red triangle down','🔷':'blue diamond large','🔶':'orange diamond large','🏷️':'label tag price','🔖':'bookmark save','🚩':'red flag warning','🏁':'finish flag race','🏴':'black flag','🏳️':'white flag peace surrender','🚫':'prohibited banned no','⛔':'no entry stop','🔞':'adult eighteen','📵':'no phone','🛑':'stop octagon','♾️':'infinity loop endless',
};

const emojis = [
  ['Smileys', '😀','😃','😄','😁','😆','😅','😂','🤣','🥲','😊','😇','🥰','😍','🤩','😘','😗','😙','😚','🙂','🤭','😉','😌','😏','😒','😞','😔','😟','😕','🙁','☹️','😣','😖','😫','😩','🥺','😢','😭','😤','😠','😡','🤬','🤯','😳','🥵','🥶','😱','😨','😰','🤔','🫡','🤗','😶','😑','😬','🙄','😯','😲','🥱','😴','😵','🤐','🥴','🤧','😷','🤒','😈','👿','💀','👻','😺','😸','😹','😻','😎','🤓','🧐'],
  ['Hearts & Love', '❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💕','💞','💓','💗','💖','💘','💝','💟','❣️','💔','❤️‍🔥','❤️‍🩹','💋','😘','🥰','😍','🫶','🫂','💑','💏','💐','🌹','🌷','💒','💍','🎁','🪷','🫧'],
  ['People & Hands', '👋','🤚','🖐️','✋','🖖','🤙','👌','🤌','🤏','✌️','🤞','🤟','🤘','👈','👉','👆','🖕','👇','☝️','👍','👎','✊','👊','🤛','🤜','👏','🙌','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','👀','🫦','🧠','🫀','🦷','🦴','🙈','🙉','🙊','🧑','👦','👧','🧒','👶','👩','👨','🧓','👴','👵','👩‍💻','👨‍💻','👩‍🎨','👨‍🎨','👩‍🏫','👮','💂','🧙','🧝','🧛','🧟','🧞'],
  ['Animals', '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🐔','🐧','🐦','🦆','🦅','🦉','🦇','🐺','🐴','🦄','🐝','🦋','🐌','🐞','🐜','🦟','🐢','🐍','🦎','🐙','🦑','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🦭','🐘','🦒','🦓','🦍','🦏','🐊','🦕','🦖','🦔','🐿️','🦫','🦦','🦥','🦜','🐓','🦃','🐇','🐈','🐩','🦮','🐕','🐈‍⬛','🪲','🦗','🦂'],
  ['Food & Drink', '🍎','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍒','🍑','🥭','🍍','🥝','🍅','🥑','🥦','🥕','🌽','🌶️','🧄','🥔','🍠','🥐','🍞','🥖','🥨','🧀','🥚','🍳','🥞','🧇','🥓','🥩','🍗','🍖','🍔','🍟','🌭','🍕','🥪','🌮','🌯','🥗','🍜','🍣','🍱','🍛','🍲','🍤','🍙','🍚','🍘','🍡','🧁','🎂','🍰','🍦','🍩','🍪','🍫','🍭','🍬','☕','🍵','🧋','🥤','🧃','🍺','🍻','🥂','🍷','🍸','🍹','🍾','🥃','🧊','💧'],
  ['Nature', '🌸','🌺','🌻','🌹','🌷','🪷','🌱','🌿','🍀','🍃','🍂','🍁','🍄','🌾','🌵','🎄','🌲','🌳','🎋','🌴','🪴','🪸','🌊','🌋','🏔️','⛰️','☀️','🌤️','⛅','🌥️','☁️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌈','⚡','🔥','💧','🌬️','🌀','🌪️','🌙','🌑','🌕','⭐','🌟','💫','✨','☄️','🌠','🌌','🌍','🌎','🌏','🪐','🌅','🌄','🌃','🌆','🌇','🌉'],
  ['Travel & Places', '✈️','🚀','🛸','🚁','🛩️','⛵','🚢','🚂','🚄','🚅','🚗','🚕','🚙','🚌','🏎️','🚓','🚑','🚒','🛻','🚲','🛴','🛵','🏍️','🚜','⛽','🚦','🚥','🗺️','🧭','🏠','🏡','🏢','🏦','🏥','🏨','🏪','🏫','🏭','🏰','🏯','🗼','🗽','🗿','🛕','⛩️','🕌','🎡','🎢','🎠','🏖️','🏜️','🏝️','🏕️','🧳','🪂'],
  ['Activities', '⚽','🏀','🏈','⚾','🥎','🏐','🏉','🎾','🥏','🎱','🏓','🏸','🥊','🥋','⛳','🎣','🤿','🏋️','🤸','🏊','🚴','🧘','⛷️','🏂','🤺','🏇','🧗','🤼','🤾','⛹️','🏌️','🏆','🥇','🥈','🥉','🏅','🎖️','🎭','🎨','🎬','🎤','🎧','🎼','🎵','🎶','🎹','🥁','🎷','🎺','🎸','🪕','🎻','🪗','🎲','♟️','🎮','🕹️','🧩','🎯','🎳','🎰','🪄','🎪','🎉','🎊','🎈','🎀','🎁','🎗️'],
  ['Work & Office', '💼','📅','📊','📈','📉','🧾','💻','🖥️','🖨️','⌨️','🖱️','📱','☎️','📞','📟','📠','📧','📝','✏️','🖊️','🖋️','📎','📌','📍','🔒','🔓','🗂️','📂','📁','📋','📜','📄','📃','⏰','⏱️','⌚','💰','💵','💳','🏦','📣','📢','💡','🎯','🏆','🔑','🗝️','✅','❌','⚠️','💎','🤝','📬','📫','🗃️','🗄️','📦','🌐','🔭','🔬','🧪','🛡️','🔐','🪪','🖇️'],
  ['Symbols & Signs', '💯','✅','❌','⭕','❗','❓','‼️','⁉️','🔴','🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','⬆️','⬇️','⬅️','➡️','↗️','↘️','↙️','↖️','↕️','↔️','🔄','🔃','🔁','🔂','▶️','⏩','⏭️','⏯️','⏸️','⏹️','⏺️','🆕','🆗','🆒','🆓','🆙','🔔','🔕','🔇','🔊','💬','💭','🗯️','♻️','✴️','🔰','💠','🔮','🔸','🔹','🔺','🔻','🔷','🔶','🏷️','🔖','🚩','🏁','🏴','🏳️','🚫','⛔','🔞','📵','🛑','♾️'],
];

export default function EmojiTool() {
  const [query, setQuery] = useState('');
  const [copied, setCopied] = useState('');
  const q = query.trim().toLowerCase();
  const filtered = useMemo(() => {
    if (!q) return emojis;
    return emojis
      .map(([cat, ...items]) => [
        cat,
        ...items.filter(e =>
          cat.toLowerCase().includes(q) ||
          e.includes(query) ||
          names[e]?.toLowerCase().includes(q)
        ),
      ])
      .filter(x => x.length > 1);
  }, [q, query]);
  const copy = async e => {
    try { await navigator.clipboard.writeText(e); } catch { /* blocked in some envs */ }
    setCopied(e);
    setTimeout(() => setCopied(''), 1400);
  };
  return (
    <>
      <label className="search-box">
        <Icon name="search"/>
        <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name — e.g. thumbs up, dog, pizza…"/>
      </label>
      {copied && <div className="toast"><Icon name="check" size={16}/> {copied} copied</div>}
      {filtered.length === 0 && <p style={{color:'#8a93a3',textAlign:'center',padding:'24px 0'}}>No emojis match &ldquo;{query}&rdquo;</p>}
      <div className="emoji-groups">
        {filtered.map(([cat, ...items]) => (
          <div key={cat}>
            <h3>{cat} <span style={{fontWeight:400,opacity:.5,fontSize:'0.85em'}}>({items.length})</span></h3>
            <div className="emoji-grid">
              {items.map((e, i) => (
                <button key={i} onClick={() => copy(e)} title={names[e] ?? e}>{e}</button>
              ))}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
