import { useEffect, useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';
import ToolGlyph from '../components/ToolGlyph.jsx';
import { buildInvoicePaymentMessage, calculateInvoiceTotals, createInvoicePdf, invoiceDateWarning, invoiceMoney, validateInvoice } from '../utils/simpleInvoice.js';
import './SimpleInvoicePdfTool.css';

const isoDate = date => date.toISOString().slice(0, 10);
const makeInitial = () => {
  const now = new Date(), due = new Date(now); due.setDate(due.getDate() + 14);
  return { businessName: '', abn: '', businessAddress: '', businessEmail: '', businessPhone: '', website: '', clientName: '', clientEmail: '', clientAddress: '', invoiceNumber: '', invoiceDate: isoDate(now), dueDate: isoDate(due), currency: 'AUD', gstMode: 'added', paymentInstructions: 'Please pay by bank transfer and include the invoice number as the reference.', accountName: '', bsb: '', accountNumber: '', paymentReference: '', paymentLink: '', notes: '', terms: 'Payment due by the date shown above.', footerText: 'Thank you for your business.', items: [{ id: 1, description: '', quantity: '1', unitPrice: '' }] };
};

export default function SimpleInvoicePdfTool() {
  const [data, setData] = useState(makeInitial), [preview, setPreview] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [pdfResult, setPdfResult] = useState(null), [copied, setCopied] = useState(false);
  const totals = useMemo(() => calculateInvoiceTotals(data.items, data.gstMode), [data.items, data.gstMode]);
  const dateWarning = invoiceDateWarning(data.invoiceDate, data.dueDate);
  useEffect(() => () => { if (pdfResult?.url) URL.revokeObjectURL(pdfResult.url); }, [pdfResult]);
  const set = (name, value) => { setData(current => ({ ...current, [name]: value })); setPreview(null); setPdfResult(null); setError(''); };
  const updateItem = (id, name, value) => { setData(current => ({ ...current, items: current.items.map(item => item.id === id ? { ...item, [name]: value } : item) })); setPreview(null); setPdfResult(null); setError(''); };
  const addItem = () => setData(current => ({ ...current, items: [...current.items, { id: Math.max(0, ...current.items.map(item => item.id)) + 1, description: '', quantity: '1', unitPrice: '' }] }));
  const removeItem = id => setData(current => ({ ...current, items: current.items.filter(item => item.id !== id) }));
  const previewInvoice = () => { const validation = validateInvoice(data); if (validation) { setError(validation); return; } setPreview(structuredClone(data)); setError(''); };
  const makePdf = async () => {
    const validation = validateInvoice(data); if (validation) { setError(validation); return; }
    setBusy(true); setError('');
    try {
      const bytes = await createInvoicePdf(data);
      const url = URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' }));
      setPdfResult({ url, size: bytes.length, name: `${(data.invoiceNumber || 'invoice').replace(/[^a-z0-9_-]+/gi, '-')}.pdf` });
      if (!preview) setPreview(structuredClone(data));
    } catch (pdfError) { setError(pdfError.message || 'The invoice PDF could not be created.'); }
    setBusy(false);
  };
  const copyPayment = async () => { await navigator.clipboard.writeText(buildInvoicePaymentMessage(data, totals)); setCopied(true); window.setTimeout(() => setCopied(false), 1400); };
  const clear = () => { setData(makeInitial()); setPreview(null); setPdfResult(null); setError(''); };

  return <div className="sip-root">
    <div className="sip-local"><ToolGlyph name="fileText" size={22}/><div><strong>Simple invoice, made locally</strong><span>No account, cloud storage, accounting integration, or backend.</span></div></div>
    <section className="sip-editor">
      <FormSection title="Business details" icon="business"><div className="sip-grid"><Field label="Business name" value={data.businessName} onChange={value => set('businessName', value)}/><Field label="ABN" value={data.abn} onChange={value => set('abn', value)}/><Field label="Address" value={data.businessAddress} onChange={value => set('businessAddress', value)} wide/><Field label="Email" type="email" value={data.businessEmail} onChange={value => set('businessEmail', value)}/><Field label="Phone" type="tel" value={data.businessPhone} onChange={value => set('businessPhone', value)}/><Field label="Website" type="url" value={data.website} onChange={value => set('website', value)} wide/></div></FormSection>
      <FormSection title="Client details" icon="userRound"><div className="sip-grid"><Field label="Client name" hint="Recommended" value={data.clientName} onChange={value => set('clientName', value)}/><Field label="Client email" type="email" value={data.clientEmail} onChange={value => set('clientEmail', value)}/><Field label="Client address" value={data.clientAddress} onChange={value => set('clientAddress', value)} wide/></div></FormSection>
      <FormSection title="Invoice details" icon="fileText"><div className="sip-grid sip-grid-three"><Field label="Invoice number" hint="Recommended" value={data.invoiceNumber} onChange={value => set('invoiceNumber', value)}/><Field label="Invoice date" type="date" value={data.invoiceDate} onChange={value => set('invoiceDate', value)}/><Field label="Due date" type="date" value={data.dueDate} onChange={value => set('dueDate', value)}/><label>Currency<select value={data.currency} onChange={event => set('currency', event.target.value)}>{['AUD','NZD','USD','GBP','EUR'].map(currency => <option key={currency}>{currency}</option>)}</select></label><label className="sip-gst-select">GST mode<select aria-label="GST mode" value={data.gstMode} onChange={event => set('gstMode', event.target.value)}><option value="none">No GST</option><option value="included">GST included</option><option value="added">GST added on top</option></select></label></div>{dateWarning && <p className="sip-warning"><ToolGlyph name="warning" size={16}/>{dateWarning}</p>}</FormSection>
      <FormSection title="Line items" icon="listChecks" action={<button className="button secondary compact" onClick={addItem}><ToolGlyph name="plus" size={15}/> Add line item</button>}><div className="sip-items"><div className="sip-item-head"><span>Description</span><span>Quantity</span><span>Unit price</span><span>Amount</span><span/></div>{data.items.map((item, index) => <div className="sip-item" key={item.id}><label><span className="sr-only">Item {index + 1} description</span><input aria-label={`Item ${index + 1} description`} value={item.description} onChange={event => updateItem(item.id, 'description', event.target.value)} placeholder="Website support"/></label><label><span className="sr-only">Item {index + 1} quantity</span><input aria-label={`Item ${index + 1} quantity`} type="number" min="0.01" step="0.01" value={item.quantity} onChange={event => updateItem(item.id, 'quantity', event.target.value)}/></label><label><span className="sr-only">Item {index + 1} unit price</span><input aria-label={`Item ${index + 1} unit price`} type="number" min="0" step="0.01" value={item.unitPrice} onChange={event => updateItem(item.id, 'unitPrice', event.target.value)} placeholder="0.00"/></label><strong>{invoiceMoney((Number(item.quantity) || 0) * (Number(item.unitPrice) || 0), data.currency)}</strong><button aria-label={`Remove item ${index + 1}`} onClick={() => removeItem(item.id)} disabled={data.items.length === 1}><ToolGlyph name="trash" size={16}/></button></div>)}</div><Totals totals={totals} currency={data.currency} included={data.gstMode === 'included'}/></FormSection>
      <FormSection title="Payment details" icon="dollar"><div className="sip-grid"><label className="wide">Payment instructions<textarea rows="3" value={data.paymentInstructions} onChange={event => set('paymentInstructions', event.target.value)}/></label><Field label="Account name" value={data.accountName} onChange={value => set('accountName', value)}/><Field label="BSB" value={data.bsb} onChange={value => set('bsb', value)}/><Field label="Account number" value={data.accountNumber} onChange={value => set('accountNumber', value)}/><Field label="Payment reference" value={data.paymentReference} onChange={value => set('paymentReference', value)} placeholder={data.invoiceNumber}/><Field label="Payment link" type="url" value={data.paymentLink} onChange={value => set('paymentLink', value)} wide/></div></FormSection>
      <FormSection title="Notes and terms" icon="text"><div className="sip-grid"><label>Notes<textarea rows="4" value={data.notes} onChange={event => set('notes', event.target.value)}/></label><label>Terms<textarea rows="4" value={data.terms} onChange={event => set('terms', event.target.value)}/></label><Field label="Footer text" value={data.footerText} onChange={value => set('footerText', value)} wide/></div></FormSection>
      {error && <p className="sip-error" role="alert">{error}</p>}
      <div className="sip-actions"><button className="button primary" onClick={previewInvoice}><ToolGlyph name="fileSearch" size={17}/> Preview invoice</button><button className="button secondary" onClick={makePdf} disabled={busy}><ToolGlyph name="download" size={17}/>{busy ? 'Creating PDF…' : 'Create PDF'}</button><button className="button secondary" onClick={copyPayment}><Icon name={copied ? 'check' : 'copy'} size={17}/>{copied ? 'Copied payment message' : 'Copy payment message'}</button><button className="button secondary" onClick={clear}>Clear form</button></div>
      {pdfResult && <div className="sip-pdf-ready"><div><strong>Invoice PDF ready</strong><span>{Math.max(1, Math.round(pdfResult.size / 1024))} KB · generated in your browser</span></div><a className="button primary compact" href={pdfResult.url} download={pdfResult.name}>Download PDF</a></div>}
    </section>
    {preview && <InvoicePreview data={preview}/>} 
    <div className="sip-disclaimer"><Icon name="shield" size={18}/><p><strong>Private and intentionally simple.</strong> Invoice details stay in your browser. This document does not replace accounting, tax, or legal advice.</p></div>
  </div>;
}

function FormSection({ title, icon, action, children }) { return <section className="sip-section"><header><div><ToolGlyph name={icon} size={18}/><h3>{title}</h3></div>{action}</header>{children}</section>; }
function Field({ label, hint, value, onChange, type = 'text', wide = false, placeholder = '' }) { return <label className={wide ? 'wide' : ''}>{label}{hint && <> <span>{hint}</span></>}<input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder}/></label>; }
function Totals({ totals, currency, included }) { return <div className="sip-totals"><div><span>{included ? 'Subtotal ex GST' : 'Subtotal'}</span><strong>{invoiceMoney(totals.subtotal, currency)}</strong></div><div><span>GST</span><strong>{invoiceMoney(totals.gst, currency)}</strong></div><div className="total"><span>Total</span><strong>{invoiceMoney(totals.total, currency)}</strong></div></div>; }
function InvoicePreview({ data }) {
  const totals = calculateInvoiceTotals(data.items, data.gstMode);
  return <section className="sip-preview" aria-label="Invoice preview"><header><div><strong>{data.businessName || 'Business name'}</strong><span>{[data.abn && `ABN ${data.abn}`, data.businessEmail, data.businessPhone].filter(Boolean).join(' · ')}</span></div><h2>INVOICE</h2></header><div className="sip-preview-meta"><div><span>Bill to</span><strong>{data.clientName || 'Client name'}</strong><p>{data.clientAddress}</p></div><dl><dt>Invoice</dt><dd>{data.invoiceNumber || '-'}</dd><dt>Date</dt><dd>{data.invoiceDate}</dd><dt>Due</dt><dd>{data.dueDate}</dd></dl></div><div className="sip-preview-table"><div className="head"><span>Description</span><span>Qty</span><span>Price</span><span>Amount</span></div>{data.items.map(item => <div key={item.id}><strong>{item.description}</strong><span>{item.quantity}</span><span>{invoiceMoney(item.unitPrice, data.currency)}</span><span>{invoiceMoney(Number(item.quantity) * Number(item.unitPrice), data.currency)}</span></div>)}</div><Totals totals={totals} currency={data.currency} included={data.gstMode === 'included'}/>{buildInvoicePaymentMessage(data, totals) && <div className="sip-preview-payment"><strong>Payment details</strong><pre>{buildInvoicePaymentMessage(data, totals)}</pre></div>}{data.notes && <p><strong>Notes:</strong> {data.notes}</p>}{data.footerText && <footer>{data.footerText}</footer>}</section>;
}
